name: crypt_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.3

dependencies:
  alfred: ^1.1.0+2
  args: ^2.3.0
  crypto: ^3.0.3
  cryptography: ^2.5.0
  postgres: ^2.6.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
